django_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('mainapp.urls', namespace='blog')),
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

mainapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class PublishedManager(models.Manager):
    def get_queryset(self):
        return (super().get_queryset().
                filter(status=Post.Status.PUBLISHED))


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def post_list(request):
    posts = Post.published.all()
    return render(request, 'blog/post/list.html',
                  {'posts': posts})


def post_detail(request, id):
    post = get_object_or_404(Post, id=id,
                             status=Post.Status.PUBLISHED)
    return render(request, 'blog/post/detail.html',
                  {'post': post})

mainapp/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            margin:0;
            padding:0;
            font-family:helvetica, sans-serif;
        }

        a {
            color:#00abff;
            text-decoration:none;
        }

        h1 {
            font-weight:normal;
            border-bottom:1px solid #bbb;
            padding:0 0 10px 0;
        }

        h2 {
            font-weight:normal;
            margin:30px 0 0;
        }

        #content {
            float:left;
            width:60%;
            padding:0 0 0 30px;
        }

        #sidebar {
            float:right;
            width:30%;
            padding:10px;
            background:#efefef;
            height:100%;
        }

        p.date {
            color:#ccc;
            font-family: georgia, serif;
            font-size: 12px;
            font-style: italic;
        }

        /* pagination */
        .pagination {
            margin:40px 0;
            font-weight:bold;
        }

        /* forms */
        label {
            float:left;
            clear:both;
            color:#333;
            margin-bottom:4px;
        }
        input, textarea {
            clear:both;
            float:left;
            margin:0 0 10px;
            background:#ededed;
            border:0;
            padding:6px 10px;
            font-size:12px;
        }
        input[type=submit] {
            font-weight:bold;
            background:#00abff;
            color:#fff;
            padding:10px 20px;
            font-size:14px;
            text-transform:uppercase;
        }
        .errorlist {
            color:#cc0033;
            float:left;
            clear:both;
            padding-left:10px;
        }

        /* comments */
        .comment {
            padding:10px;
        }
        .comment:nth-child(even) {
            background:#efefef;
        }
        .comment .info {
            font-weight:bold;
            font-size:12px;
            color:#666;
        }
    </style>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my blog.</p>
    </div>
</body>
</html>

mainapp/templates/blog/post/detail.html
{%extends "blog/base.html"%}
{%block title%}{{post.title}}{%endblock%}

{%block content%}
    <h1>{{post.title}}</h1>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    {{post.body|linebreaks}}
{%endblock%}

mainapp/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
    <h2>
        <a href = "{% url 'blog:post_detail' post.id %}">
            {{post.title}}
        </a>
    </h2>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
    {{post.body|truncatewords:30|linebreaks}}
    {%endfor%}
{% endblock %}